spring:
  application:
    name: RedditProducerService
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

reddit:
  subreddits: interviews,leetcode,big_tech_interviews
  interval-seconds: 10

topic:
  name: reddit.raw.posts