server:
  port: 8082

spring:
  application:
    name: InterviewService

  datasource:
    url: jdbc:postgresql://localhost:5432/interviews_db
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework: INFO
    com.coconutslices: DEBUG