server:
  port: 8083

spring:
  application:
    name: AuthService
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: USERNAME
    password: PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: thisismyreallyreallywonderfulsecret!
  expiration: 3600000

#logging:
#  level:
#    org.springframework: INFO
#    com.coconutslices: WARN